---
- name: install dirmngr
  apt: name="{{ item }}" state=present
  with_items:
  - gnupg2
  - dirmngr
  when:
  - ansible_distribution == "Debian"
  - ansible_distribution_major_version == "9"

- name: add git ppa
  apt_repository:
    repo: 'ppa:git-core/ppa'
    codename: trusty
    filename: git
    state: present

- name: update cache
  shell: apt-get update

- name: install git
  apt: name=git state=latest
