---
- name: install dirmngr
  apt: name="{{ item }}" state=present force=yes
  with_items:
  - gnupg2
  - dirmngr
  when:
  - ansible_distribution == "Debian"
  - ansible_distribution_major_version == "9"

- name: add git ppa
  apt_repository:
    repo: 'ppa:git-core/ppa'
    codename: trusty
    filename: git
    state: present

- name: update cache
  shell: apt-get update

- name: install git
  apt: name=git state=latest force=yes

- name: add the user custom gitconfig
  template:
    src: .my_gitconfig.j2
    dest: "{{ the_user_my_gitconfig_path }}"
    owner: "{{ the_user }}"
    mode: 0600

- name: include custom gitconfig to default gitconfig
  blockinfile:
    dest: "{{ the_user_dir }}/.gitconfig"
    create: yes
    owner: "{{ the_user }}"
    block: |
      [include]
        path = "{{ the_user_my_gitconfig_path }}"

- name: ensure default user custom bashrc git config
  template:
    src: .my_bashrc_git.j2
    dest: "{{ the_user_my_bashrc_git_path }}"
    owner: "{{ the_user }}"
    mode: 0600

- name: ensure default user bashrc includes custom bashrc git config
  lineinfile:
    dest: "{{ the_user_dir }}/.bashrc"
    create: yes
    owner: "{{ the_user }}"
    line: "source {{ the_user_my_bashrc_git_path }}"
